using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._CitadelStation.Woundmed.UI;

[GenerateTypedNameReferences]
public sealed partial class TargetControl : UIWidget
{
    public TargetControl()
    {
        RobustXamlLoader.Load(this);
        // PressButton.OnPressed += _ => Logger.Debug("Foo");
        TargetChoice.Texture = Theme.ResolveTexture("target_doll");
    }
}
