using System.Linq;
using Content.Shared._CitadelStation.WoundMed.Constants;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._CitadelStation.Woundmed.UI;

[GenerateTypedNameReferences]
public sealed partial class TargetControl : UIWidget
{
    private readonly Dictionary<TargetChooserBodyPart, Button> _bodypartButtons;

    private readonly TargetWidgetController _controller = default!;
    public TargetControl()
    {

        _controller = UserInterfaceManager.GetUIController<TargetWidgetController>();

        RobustXamlLoader.Load(this);
        // PressButton.OnPressed += _ => Logger.Debug("Foo");
        TargetChoice.Texture = Theme.ResolveTexture("target_doll");

        _bodypartButtons = new Dictionary<TargetChooserBodyPart, Button> {
            {TargetChooserBodyPart.body, Torso},
            {TargetChooserBodyPart.head, Head},
            {TargetChooserBodyPart.larm, LeftArm},
            {TargetChooserBodyPart.rarm, RightArm},
            {TargetChooserBodyPart.lleg, LeftLeg},
            {TargetChooserBodyPart.rleg, RightLeg}
        };
        foreach (var bodypartFunctionMapEntry in _bodypartButtons){
            bodypartFunctionMapEntry.Value.OnPressed += _ => SetActiveBodypartTarget(bodypartFunctionMapEntry.Key);
        }
    }

    private void SetActiveBodypartTarget(TargetChooserBodyPart key)
    {
        //throw new NotImplementedException();
        _controller.OnChangingBodypartTarget(key);
    }
}
